Constraint simplification.
SpiNNakerManchester/PACMAN pull request #455
Opened 2022-08-04 09:28 UTC by Christian-B

This PR simplifies the Constraint stack.

There where only two Constraints still being used.
FixedKeyAndMaskConstraint
ChipAndCoreConstraint

Both could probably be done in a better way than Constraints but that is out of scope for this PR.

This PR removes a level of Abstract and removes or simplifies some of the checks on Constraints.

I considered moving the two remaining Constraint to pacman/model/constraints
If that is a good idea please comment and I will do so before this is merged in.

Should be done at the same time as:

tested by:

fixes https://github.com/SpiNNakerManchester/PACMAN/issues/440
fixes https://github.com/SpiNNakerManchester/PACMAN/issues/439

2022-08-04 13:46 UTC, andrewgait requested changes
Looks fine, just wondering whether more can be deleted.

2022-08-04 13:46 UTC, andrewgait commented on pacman/utilities/utility_calls.py
> -def check_algorithm_can_support_constraints(
I think if this is being deleted then _is_constraint_supported (above it) can go as well.

2022-08-04 13:46 UTC, andrewgait commented on pacman/utilities/utility_calls.py
> -def locate_constraints_of_type(constraints, constraint_type):
It doesn't look like locate_first_constraint_of_type(..) (the next function in this file) is used anywhere either so this can probably be deleted.

2022-09-13 13:32 UTC, Christian-B commented
All Constraints to be removed.

2022-09-13 13:32 UTC, closed without merging